apiVersion: v1
kind: Service
metadata:
  name: openlist-sftp-service
spec:
  selector:
    app: openlist
  type: NodePort
  ports:
    - name: sftp
      port: 5222
      targetPort: 5222
      nodePort: 30022
