---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openlist-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openlist
  template:
    metadata:
      labels:
        app: openlist
    spec:
      containers:
        - name: openlist
          image: openlistteam/openlist:latest
          volumeMounts:
            - name: openlist-data
              mountPath: /opt/openlist/data
      volumes:
        - name: openlist-data
          persistentVolumeClaim:
            claimName: openlist-pvc

