apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: cloudflare
    namespace: cert-manager
    envs:
      - value.env

  - name: cloudflare
    namespace: default
    envs:
      - value.env

generatorOptions:
  disableNameSuffixHash: true
